"""
Streamlit UI for the Joukowski Airfoil + Wing Designer.

Local run:
    pip install -r requirements.txt
    streamlit run app.py

Repository layout expected:
    app.py                      this file (UI)
    plots.py                    all figure construction
    joukowski_designer_v2.py    the aerodynamic engine (not generated by the UI)
    requirements.txt
    .streamlit/config.toml

The engine module is imported, never modified, by this UI.
"""

import copy
import hashlib
import inspect
import io
import json
import shutil
import tempfile
import zipfile
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

# =========================================================================
# PAGE CONFIG - must be the first Streamlit call
# =========================================================================
st.set_page_config(
    page_title="Joukowski Airfoil & Wing Designer",
    page_icon="✈",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# =========================================================================
# ENGINE + FIGURE IMPORTS
# A missing engine file is the most likely deployment failure, so it fails
# with an instruction instead of a raw traceback.
# =========================================================================
try:
    from joukowski_designer_v2 import (
        VERSION,
        default_config_template,
        calculate_wing_geometry,
        optimize_airfoil,
        alpha_sweep,
        find_design_point,
        sample_sweep_at_alpha,
        compressibility_warning,
        approx_cl_max,
        generate_joukowski_airfoil,
        reorder_airfoil_from_trailing_edge,
        export_airfoil_files,
        export_sweep_csv,
        export_cp_distribution,
        export_wing_files,
        write_summary_sheet,
        write_run_manifest,
    )
    import plots as P
except ModuleNotFoundError as exc:  # pragma: no cover - deployment guard
    st.error(
        f"Missing module: **{exc.name}**\n\n"
        "This app needs three Python files in the same folder:\n\n"
        "- `app.py` (this file)\n"
        "- `plots.py`\n"
        "- `joukowski_designer_v2.py` — the aerodynamic engine\n\n"
        "Commit all three to the repository root, then reboot the app."
    )
    st.stop()

# =========================================================================
# LIGHT-THEME CSS
# .streamlit/config.toml sets the light theme properly; this is the
# belt-and-braces layer for widgets the theme does not reach.
# =========================================================================
st.markdown("""
<style>
    /* FORCE light theme regardless of any global Streamlit setting */
    html, body, [data-testid="stAppViewContainer"], [data-testid="stApp"],
    .main, .block-container, [data-testid="stHeader"],
    section.main, [data-testid="stSidebar"] {
        background-color: #FFFFFF !important;
        color: #1A2332 !important;
    }
    [data-testid="stAppViewContainer"] > .main { background-color: #FFFFFF !important; }
    [data-testid="stHeader"] { background: transparent !important; }

    /* base spacing */
    .block-container {
        padding-top: 1.6rem;
        padding-bottom: 3rem;
        max-width: 1280px;
    }

    /* typography */
    html, body, [class^="css"], [class*=" css"] {
        font-family: "Inter", -apple-system, "Segoe UI", Roboto, "Helvetica Neue",
                     Arial, sans-serif;
    }
    h1 { color: #1A2332 !important; font-weight: 600; font-size: 28px;
         letter-spacing: -0.3px; margin-bottom: 0.25rem; }
    h2 { color: #1A2332 !important; font-weight: 600; font-size: 20px; }
    h3 { color: #1A2332 !important; font-weight: 600; font-size: 17px; }
    h4, h5 { color: #1A2332 !important; font-weight: 600; }
    p, div, span, label { color: #2A3547; }
    .stMarkdown p { color: #3A4557 !important; }
    .stMarkdown strong { color: #1A2332 !important; }

    /* subtle captions */
    [data-testid="stCaptionContainer"], .stCaption,
    [data-testid="stCaptionContainer"] p { color: #6B7788 !important; }

    /* tab bar - allow horizontal scroll instead of squashing labels */
    div[data-baseweb="tab-list"] {
        gap: 2px;
        background: #FFFFFF !important;
        border: none;
        border-bottom: 1px solid #DDE3EC;
        padding: 0;
        border-radius: 0;
        overflow-x: auto;
        overflow-y: hidden;
        scrollbar-width: thin;
    }
    button[data-baseweb="tab"] {
        background: transparent !important;
        border-radius: 0 !important;
        padding: 10px 18px !important;
        color: #6B7788 !important;
        font-weight: 500 !important;
        font-size: 14px !important;
        border-bottom: 2px solid transparent !important;
        margin-bottom: -1px !important;
        white-space: nowrap;
        flex: 0 0 auto;
    }
    button[data-baseweb="tab"]:hover { color: #1A2332 !important; }
    button[data-baseweb="tab"][aria-selected="true"] {
        background: transparent !important;
        color: #1A2332 !important;
        border-bottom: 2px solid #2C5282 !important;
        box-shadow: none !important;
    }
    button[data-baseweb="tab"] p { color: inherit !important; }

    /* metric cards */
    div[data-testid="stMetric"] {
        background: #FAFBFD !important;
        border: 1px solid #E4E9F0;
        padding: 14px 18px;
        border-radius: 4px;
        overflow-wrap: anywhere;
    }
    div[data-testid="stMetricValue"] {
        color: #1A2332 !important;
        font-size: 22px !important;
        font-weight: 600 !important;
    }
    div[data-testid="stMetricLabel"], div[data-testid="stMetricLabel"] p {
        color: #6B7788 !important;
        font-size: 12px !important;
        text-transform: uppercase;
        letter-spacing: 0.4px;
    }

    /* buttons - explicit for all variants */
    div.stButton > button,
    div.stDownloadButton > button {
        border-radius: 4px !important;
        font-weight: 500 !important;
        border: 1px solid #DDE3EC !important;
        background-color: #FFFFFF !important;
        color: #1A2332 !important;
    }
    div.stButton > button:hover,
    div.stDownloadButton > button:hover {
        border-color: #2C5282 !important;
        color: #2C5282 !important;
        background-color: #FFFFFF !important;
    }
    div.stButton > button p, div.stDownloadButton > button p,
    div.stButton > button span, div.stDownloadButton > button span {
        color: inherit !important;
    }
    div.stButton > button[kind="primary"],
    div.stDownloadButton > button[kind="primary"] {
        background-color: #2C5282 !important;
        color: #FFFFFF !important;
        border: 1px solid #2C5282 !important;
        padding: 9px 24px !important;
        font-weight: 500 !important;
        letter-spacing: 0.2px !important;
    }
    div.stButton > button[kind="primary"]:hover,
    div.stDownloadButton > button[kind="primary"]:hover {
        background-color: #1E3A5F !important;
        border-color: #1E3A5F !important;
        color: #FFFFFF !important;
    }
    div.stButton > button[kind="primary"] p,
    div.stDownloadButton > button[kind="primary"] p { color: #FFFFFF !important; }

    /* file uploader */
    [data-testid="stFileUploader"] section {
        background-color: #FAFBFD !important;
        border: 1px dashed #B0BCC9 !important;
        color: #1A2332 !important;
    }
    [data-testid="stFileUploader"] section * { color: #1A2332 !important; }
    [data-testid="stFileUploader"] small,
    [data-testid="stFileUploader"] section small { color: #6B7788 !important; }
    [data-testid="stFileUploader"] button,
    [data-testid="stFileUploaderDropzoneInstructions"] + button {
        background-color: #FFFFFF !important;
        color: #1A2332 !important;
        border: 1px solid #DDE3EC !important;
        border-radius: 4px !important;
    }
    [data-testid="stFileUploader"] button:hover {
        border-color: #2C5282 !important; color: #2C5282 !important;
    }
    [data-testid="stFileUploader"] button p,
    [data-testid="stFileUploader"] button span { color: inherit !important; }
    [data-testid="stFileUploader"] svg { color: #6B7788 !important; fill: #6B7788 !important; }

    /* inputs */
    input, textarea, select,
    [data-baseweb="input"], [data-baseweb="select"] {
        background-color: #FFFFFF !important;
        color: #1A2332 !important;
        border-color: #DDE3EC !important;
    }
    [data-baseweb="input"] > div { background-color: #FFFFFF !important; }
    [data-baseweb="select"] > div { background-color: #FFFFFF !important; }
    [data-testid="stNumberInput"] button {
        background-color: #FAFBFD !important;
        color: #1A2332 !important;
        border-color: #DDE3EC !important;
    }

    /* alerts */
    div[data-testid="stAlert"] { border-radius: 4px; border: 1px solid #E4E9F0; }
    div[data-testid="stAlert"] p { color: #1A2332 !important; }

    /* dataframes */
    div[data-testid="stDataFrame"] { border-radius: 4px; border: 1px solid #E4E9F0; }

    /* text and code blocks */
    pre, code, .stCode, .stCodeBlock,
    [data-testid="stText"], [data-testid="stText"] pre,
    [data-testid="stMarkdownContainer"] pre,
    [data-testid="stMarkdownContainer"] code {
        background-color: #FAFBFD !important;
        color: #1A2332 !important;
        border: 1px solid #E4E9F0 !important;
        border-radius: 4px !important;
    }
    pre * { color: #1A2332 !important; }

    hr { margin: 1.2rem 0; border-color: #E4E9F0; }

    /* expander */
    details {
        background-color: #FAFBFD !important;
        border: 1px solid #E4E9F0 !important;
        border-radius: 4px !important;
    }
    details summary, details summary p { color: #1A2332 !important; }

    /* popover / radio / toggle / slider */
    [data-testid="stPopover"] button {
        background-color: #FFFFFF !important;
        color: #1A2332 !important;
        border: 1px solid #DDE3EC !important;
    }
    [data-testid="stRadio"] label, [data-testid="stToggle"] label,
    [data-testid="stSlider"] label, [data-testid="stCheckbox"] label {
        color: #1A2332 !important;
    }

    /* Plotly: white canvas, and a modebar that stays visible on white */
    .js-plotly-plot .plotly .modebar {
        background: rgba(255,255,255,0.92) !important;
        border: 1px solid #E4E9F0;
        border-radius: 4px;
    }
    .js-plotly-plot .plotly .modebar-btn path { fill: #6B7788 !important; }
    .js-plotly-plot .plotly .modebar-btn:hover path { fill: #2C5282 !important; }
    .stPlotlyChart {
        border: 1px solid #E4E9F0;
        border-radius: 4px;
        background: #FFFFFF;
        padding: 4px;
    }
</style>
""", unsafe_allow_html=True)


# =========================================================================
# SMALL UTILITIES
# =========================================================================
def fill(fn):
    """
    Kwargs that make a widget fill its container, for whatever Streamlit
    version is installed.

    Streamlit 1.49 deprecated use_container_width in favour of width; pinning
    one spelling would either break on old versions or emit deprecation
    warnings on new ones, so the parameter is chosen by introspection.
    """
    try:
        params = inspect.signature(fn).parameters
    except (TypeError, ValueError):
        return {}
    if "width" in params:
        return {"width": "stretch"}
    if "use_container_width" in params:
        return {"use_container_width": True}
    return {}


FILL_DF = fill(st.dataframe)
FILL_BTN = fill(st.button)
FILL_DL = fill(st.download_button)
FILL_PLOTLY = fill(st.plotly_chart)

PLOTLY_CONFIG = {
    "displaylogo": False,
    "modeBarButtonsToRemove": ["select2d", "lasso2d"],
    "toImageButtonOptions": {"format": "png", "scale": 2,
                             "filename": "joukowski_wing_3d"},
    "scrollZoom": True,
}


def show_df(df, height=None, index=False):
    kw = dict(FILL_DF)
    if height is not None:
        kw["height"] = height
    st.dataframe(df, hide_index=not index, **kw)


def clamp(value, lo=None, hi=None, fallback=0.0):
    """
    Keep a config value inside its widget bounds.

    A hand-edited or out-of-date config JSON would otherwise make Streamlit
    raise before the Reset button is reachable.
    """
    try:
        v = float(value)
    except (TypeError, ValueError):
        v = float(fallback)
    if not np.isfinite(v):
        v = float(fallback)
    if lo is not None:
        v = max(v, float(lo))
    if hi is not None:
        v = min(v, float(hi))
    return v


def pick(options, value, default_index=0):
    """Index of value in options, tolerating a value that is not there."""
    try:
        return options.index(value)
    except (ValueError, AttributeError):
        return default_index


def merge_cfg(template, loaded):
    """
    Recursively overlay a loaded config onto the default template.

    Keys absent from the upload keep their default, and unknown keys are
    dropped, so a partial or stale JSON cannot leave the app in a state where
    a later cfg[...] lookup raises.
    """
    out = copy.deepcopy(template)
    if not isinstance(loaded, dict):
        return out
    for key, val in loaded.items():
        if key not in out:
            continue
        if isinstance(out[key], dict) and isinstance(val, dict):
            out[key] = merge_cfg(out[key], val)
        elif not isinstance(out[key], dict) and not isinstance(val, dict):
            out[key] = val
    return out


def run_key_of(cfg):
    """Short stable hash of a config, used as a cache key."""
    blob = json.dumps(cfg, sort_keys=True, default=str).encode("utf-8")
    return hashlib.sha1(blob).hexdigest()[:12]


# =========================================================================
# HEADER
# =========================================================================
col_hdr1, col_hdr2 = st.columns([4, 1])
with col_hdr1:
    st.title("Joukowski Airfoil & Wing Designer")
    st.caption(
        f"Preliminary aerodynamic design tool  ·  v{VERSION}  ·  "
        "Potential-flow with Reynolds-dependent viscous drag"
    )
with col_hdr2:
    st.write("")
    st.write("")
    with st.popover("About", **fill(st.popover)):
        st.markdown(
            "**Physics scope**\n\n"
            "- Lift: Joukowski potential flow with Prandtl–Glauert (subsonic), "
            "engineering bridge (transonic), linearized supersonic (M ≥ 1.2).\n"
            "- Drag: viscous (skin-friction and form-factor, Re-dependent), "
            "wave (transonic bridge / linearized supersonic), induced (3-D only).\n"
            "- No stall model. A warning is raised when Cl exceeds the "
            "Re-based approximate Cl_max.\n\n"
            "**Not in scope**\n\n"
            "- Boundary-layer separation, so post-stall numbers are not real.\n"
            "- Spanwise loading is not solved; the wing uses an Oswald-factor "
            "induced-drag model, and the spanwise plot is a Schrenk estimate.\n\n"
            "Validate with XFOIL, CFD, or wind-tunnel data before final use."
        )

st.divider()

# =========================================================================
# SESSION STATE
# =========================================================================
if "cfg" not in st.session_state:
    st.session_state.cfg = default_config_template()
if "results" not in st.session_state:
    st.session_state.results = None
if "cfg_upload_id" not in st.session_state:
    st.session_state.cfg_upload_id = None

# Self-heal a config that no longer matches the template.
st.session_state.cfg = merge_cfg(default_config_template(), st.session_state.cfg)
cfg = st.session_state.cfg

# =========================================================================
# INPUT TABS
# =========================================================================
st.subheader("Design inputs")

tab_flow, tab_sweep, tab_design, tab_wing, tab_adv = st.tabs([
    "Flow conditions",
    "AoA sweep",
    "Design target",
    "Wing / aircraft",
    "Advanced",
])

# ---- FLOW ----
with tab_flow:
    st.markdown("Set the freestream conditions and boundary-layer state.")
    c1, c2 = st.columns(2)
    with c1:
        cfg["flow"]["mach"] = st.number_input(
            "Mach number", min_value=0.0, max_value=3.0,
            value=clamp(cfg["flow"]["mach"], 0.0, 3.0, 0.25), step=0.05,
            help="Freestream Mach. Subsonic <0.8, transonic 0.8–1.2, supersonic ≥1.2.",
        )
        cfg["flow"]["reynolds"] = st.number_input(
            "Reynolds number", min_value=1e3, max_value=1e9,
            value=clamp(cfg["flow"]["reynolds"], 1e3, 1e9, 5e6),
            step=1.0e5, format="%.3e",
            help="Based on the reference chord (or MAC). Drives viscous drag.",
        )
        ref_opts = ["chord", "MAC"]
        cfg["flow"]["reynolds_reference"] = st.selectbox(
            "Reynolds reference length", ref_opts,
            index=pick(ref_opts, cfg["flow"]["reynolds_reference"]),
        )
    with c2:
        mode_options = ["auto", "laminar", "turbulent", "mixed"]
        cfg["flow"]["flow_regime_manual"] = st.selectbox(
            "Boundary-layer state", mode_options,
            index=pick(mode_options, cfg["flow"]["flow_regime_manual"]),
            help=("laminar / turbulent — hard override. "
                  "mixed — you pick the transition x/c. "
                  "auto — transition estimated from Re."),
        )
        if cfg["flow"]["flow_regime_manual"] == "mixed":
            cfg["flow"]["transition_xc"] = st.slider(
                "Transition x/c", min_value=0.0, max_value=1.0,
                value=clamp(cfg["flow"]["transition_xc"], 0.0, 1.0, 0.3),
                step=0.05,
                help="0 = fully turbulent from the LE, 1 = fully laminar.",
            )
        else:
            st.caption("Transition x/c is set automatically in this mode.")
        cw = compressibility_warning(cfg["flow"]["mach"])
        if cw:
            st.warning(cw)

# ---- SWEEP ----
with tab_sweep:
    st.markdown("Angle-of-attack range for the polar sweep, and how the "
                "design point is picked out of that sweep.")
    c1, c2, c3 = st.columns(3)
    with c1:
        cfg["sweep"]["alpha_start_deg"] = st.number_input(
            "α start [deg]", min_value=-90.0, max_value=90.0,
            value=clamp(cfg["sweep"]["alpha_start_deg"], -90, 90, -6.0), step=0.5)
    with c2:
        cfg["sweep"]["alpha_end_deg"] = st.number_input(
            "α end [deg]", min_value=-90.0, max_value=90.0,
            value=clamp(cfg["sweep"]["alpha_end_deg"], -90, 90, 14.0), step=0.5)
    with c3:
        cfg["sweep"]["alpha_step_deg"] = st.number_input(
            "α step [deg]", min_value=0.01, max_value=10.0,
            value=clamp(cfg["sweep"]["alpha_step_deg"], 0.01, 10.0, 0.5), step=0.1)

    span_deg = cfg["sweep"]["alpha_end_deg"] - cfg["sweep"]["alpha_start_deg"]
    n_pts = max(2, int(round(span_deg / max(cfg["sweep"]["alpha_step_deg"], 1e-6))) + 1)
    if span_deg <= 0:
        st.error("α end must be greater than α start.")
    elif n_pts > 4000:
        st.warning(f"{n_pts:,} sweep points — this will be slow. "
                   "Increase the step size.")
    else:
        st.caption(f"{n_pts} sweep points")

    st.markdown("**Design-point selection**")
    mode_labels = {
        "target_CL": "Match target CL",
        "max_LD": "Best L/D in sweep",
        "manual": "Specify AoA manually",
    }
    inv = {v: k for k, v in mode_labels.items()}
    keys = list(mode_labels.keys())
    choice = st.radio(
        "Design AoA selection mode", list(mode_labels.values()),
        index=pick(keys, cfg["sweep"]["design_alpha_mode"]),
        horizontal=True, label_visibility="collapsed",
    )
    cfg["sweep"]["design_alpha_mode"] = inv[choice]
    if cfg["sweep"]["design_alpha_mode"] == "manual":
        # Explicit None test: `or 3.0` silently replaced a legitimate 0.0.
        cur = cfg["design"]["design_alpha_deg"]
        cfg["design"]["design_alpha_deg"] = st.number_input(
            "Manual design α [deg]", min_value=-90.0, max_value=90.0,
            value=clamp(3.0 if cur is None else cur, -90, 90, 3.0), step=0.5)

# ---- DESIGN ----
with tab_design:
    st.markdown("The lift coefficient the design has to meet.")
    cfg["design"]["target_CL"] = st.number_input(
        "Target CL (aircraft) or Cl (2-D-only run)",
        min_value=0.0, max_value=3.0,
        value=clamp(cfg["design"]["target_CL"], 0.0, 3.0, 0.45), step=0.05,
        help=("With 3-D on this is the whole-aircraft CL. "
              "With 3-D off it is the 2-D section Cl."),
    )
    st.info(
        "The optimizer searches Joukowski parameters for the airfoil that hits "
        "this CL while matching the Mach-based target thickness ratio and "
        "keeping camber and design AoA within practical bounds."
    )

# ---- WING ----
with tab_wing:
    cfg["run"]["run_3d"] = st.toggle(
        "Generate 3-D wing / aircraft outputs",
        value=bool(cfg["run"]["run_3d"]),
        help="Off means 2-D airfoil analysis only.",
    )
    if cfg["run"]["run_3d"]:
        st.divider()
        st.markdown("**Planform**")
        c1, c2 = st.columns(2)
        w = cfg["wing"]
        with c1:
            w["span_m"] = st.number_input(
                "Wing span [m]", min_value=0.1, max_value=500.0,
                value=clamp(w["span_m"], 0.1, 500.0, 10.0), step=0.5)
            w["root_chord_m"] = st.number_input(
                "Root chord [m]", min_value=0.05, max_value=100.0,
                value=clamp(w["root_chord_m"], 0.05, 100.0, 2.0), step=0.1)
            w["taper_ratio"] = st.number_input(
                "Taper ratio (c_tip / c_root)", min_value=0.05, max_value=1.2,
                value=clamp(w["taper_ratio"], 0.05, 1.2, 0.45), step=0.05)
        with c2:
            w["sweep_le_deg"] = st.number_input(
                "Leading-edge sweep [deg]", min_value=-60.0, max_value=80.0,
                value=clamp(w["sweep_le_deg"], -60, 80, 0.0), step=1.0)
            w["dihedral_deg"] = st.number_input(
                "Dihedral [deg]", min_value=-30.0, max_value=30.0,
                value=clamp(w["dihedral_deg"], -30, 30, 0.0), step=0.5)
            w["wing_incidence_deg"] = st.number_input(
                "Wing incidence [deg]", min_value=-15.0, max_value=15.0,
                value=clamp(w["wing_incidence_deg"], -15, 15, 0.0), step=0.5)

        ar_preview = (w["span_m"] ** 2 /
                      (0.5 * w["root_chord_m"] * (1 + w["taper_ratio"]) * w["span_m"]))
        st.caption(f"Aspect ratio {ar_preview:.2f} · "
                   f"tip chord {w['root_chord_m'] * w['taper_ratio']:.3f} m")

        st.divider()
        st.markdown("**Aircraft reference and optional corrections**")
        c1, c2 = st.columns(2)
        with c1:
            w["cg_percent_mac"] = st.number_input(
                "CG location [% MAC]", min_value=0.0, max_value=100.0,
                value=clamp(w["cg_percent_mac"], 0, 100, 25.0), step=1.0)
            w["delta_CD0"] = st.number_input(
                "Non-wing ΔCD₀", min_value=0.0, max_value=1.0,
                value=clamp(w["delta_CD0"], 0.0, 1.0, 0.0),
                step=0.001, format="%.4f",
                help="Extra parasite drag from fuselage, tail, and the rest.")
        with c2:
            w["delta_Cm0"] = st.number_input(
                "Non-wing ΔCm₀", min_value=-1.0, max_value=1.0,
                value=clamp(w["delta_Cm0"], -1.0, 1.0, 0.0),
                step=0.001, format="%.4f",
                help="Extra zero-lift pitching moment from fuselage and tail.")
    else:
        st.info("3-D outputs are off. Turn on the toggle to define a wing "
                "planform and get 3-D wing / aircraft results.")

# ---- ADVANCED ----
with tab_adv:
    st.markdown("Change fluid properties if you are not at ISA sea level.")
    c1, c2 = st.columns(2)
    with c1:
        cfg["flow"]["kinematic_viscosity"] = st.number_input(
            "Kinematic viscosity ν [m²/s]", min_value=1e-8, max_value=1e-2,
            value=clamp(cfg["flow"]["kinematic_viscosity"], 1e-8, 1e-2, 1.46e-5),
            format="%.4e", step=1e-6)
    with c2:
        cfg["flow"]["sound_speed"] = st.number_input(
            "Sound speed a [m/s]", min_value=50.0, max_value=1000.0,
            value=clamp(cfg["flow"]["sound_speed"], 50, 1000, 340.29), step=1.0)

    v_inf = cfg["flow"]["mach"] * cfg["flow"]["sound_speed"]
    l_ref = (cfg["flow"]["reynolds"] * cfg["flow"]["kinematic_viscosity"] /
             v_inf if v_inf > 0 else float("nan"))
    st.caption(
        f"These imply V∞ = {v_inf:.2f} m/s and, for the Reynolds number "
        f"above, a reference length of {l_ref:.4f} m. "
        "Check that against your chord or MAC — the engine does not "
        "reconcile them for you."
    )

    st.divider()
    st.markdown("**Import / export config**")
    c1, c2 = st.columns(2)
    with c1:
        st.download_button(
            "Download current config as JSON",
            data=json.dumps(cfg, indent=2, default=str),
            file_name="joukowski_config.json",
            mime="application/json", **FILL_DL)
    with c2:
        uploaded = st.file_uploader(
            "Load config from JSON", type=["json"], label_visibility="collapsed")
        # Guarded by file id: the original re-loaded and called st.rerun() on
        # every rerun while a file stayed in the uploader, which loops forever.
        up_id = None
        if uploaded is not None:
            up_id = getattr(uploaded, "file_id", None) or \
                f"{uploaded.name}:{getattr(uploaded, 'size', 0)}"
        if uploaded is not None and up_id != st.session_state.cfg_upload_id:
            st.session_state.cfg_upload_id = up_id
            try:
                loaded = json.load(uploaded)
                if not isinstance(loaded, dict):
                    raise ValueError("top-level JSON must be an object")
                st.session_state.cfg = merge_cfg(default_config_template(), loaded)
                st.success("Config loaded. Click Run design to apply it.")
                st.rerun()
            except Exception as exc:
                st.error(f"Could not load that config: {exc}")

st.divider()

# =========================================================================
# RUN / RESET
# =========================================================================
c_run1, c_run2, c_run3 = st.columns([1.5, 4, 1])
with c_run1:
    run_clicked = st.button("Run design", type="primary", **FILL_BTN)
with c_run3:
    reset_clicked = st.button("Reset", **FILL_BTN)

if reset_clicked:
    st.session_state.cfg = default_config_template()
    st.session_state.results = None
    st.session_state.cfg_upload_id = None
    st.rerun()


def validate(cfg):
    """Blocking input problems, returned as messages."""
    errs = []
    if cfg["sweep"]["alpha_end_deg"] <= cfg["sweep"]["alpha_start_deg"]:
        errs.append("α end must be greater than α start.")
    if cfg["sweep"]["alpha_step_deg"] <= 0:
        errs.append("α step must be positive.")
    if cfg["run"]["run_3d"]:
        if cfg["wing"]["span_m"] <= 0 or cfg["wing"]["root_chord_m"] <= 0:
            errs.append("Span and root chord must be positive.")
        if cfg["wing"]["taper_ratio"] <= 0:
            errs.append("Taper ratio must be positive.")
    if cfg["design"]["target_CL"] <= 0:
        errs.append("Target CL must be greater than zero.")
    return errs


def run_design(cfg):
    """
    Run the full pipeline.

    Engine outputs are written to a temporary directory, read back into
    memory, and the directory is then removed. The original kept the temp
    path in session state and re-read it on every rerun, which leaks a
    directory per run and breaks the Downloads tab whenever the platform
    cleans /tmp between reruns.
    """
    warnings = []
    cw = compressibility_warning(cfg["flow"]["mach"])
    if cw:
        warnings.append(cw)
    if cfg["flow"]["reynolds"] < 1e5:
        warnings.append(
            f"Re = {cfg['flow']['reynolds']:.2e} is very low; skin-friction "
            "correlations lose accuracy below about 1e5.")
    if cfg["flow"]["reynolds"] > 1e8:
        warnings.append(
            f"Re = {cfg['flow']['reynolds']:.2e} is very high; verify the "
            "Cf model assumptions.")

    Re = cfg["flow"]["reynolds"]
    flow_mode = cfg["flow"]["flow_regime_manual"]
    x_tr = cfg["flow"]["transition_xc"]

    wing = None
    aircraft = None
    if cfg["run"]["run_3d"]:
        w = cfg["wing"]
        wing = calculate_wing_geometry(
            w["span_m"], w["root_chord_m"], w["taper_ratio"],
            w["sweep_le_deg"], w["dihedral_deg"])
        aircraft = {
            "wing_incidence_deg": float(w["wing_incidence_deg"]),
            "cg_mac_fraction": float(w["cg_percent_mac"] / 100.0),
            "delta_CD0": float(w["delta_CD0"]),
            "delta_Cm0": float(w["delta_Cm0"]),
        }

    best = optimize_airfoil(
        target_CL=cfg["design"]["target_CL"], max_mach=cfg["flow"]["mach"],
        Re=Re, flow_mode=flow_mode, x_tr=x_tr, wing=wing)

    sweep = alpha_sweep(
        best, wing, aircraft,
        cfg["sweep"]["alpha_start_deg"], cfg["sweep"]["alpha_end_deg"],
        cfg["sweep"]["alpha_step_deg"], Re=Re, flow_mode=flow_mode, x_tr=x_tr)

    design_alpha_ac = find_design_point(
        sweep, best, cfg["sweep"]["design_alpha_mode"],
        target_CL=cfg["design"]["target_CL"],
        design_alpha=cfg["design"]["design_alpha_deg"], aircraft=aircraft)

    design_vals = sample_sweep_at_alpha(sweep, design_alpha_ac)

    # Design point outside the swept range means the interpolation above was
    # an extrapolation, which the original reported as a normal result.
    a_lo = float(np.min(sweep["alpha_aircraft"]))
    a_hi = float(np.max(sweep["alpha_aircraft"]))
    if not (a_lo - 1e-9 <= design_alpha_ac <= a_hi + 1e-9):
        warnings.append(
            f"Design α = {design_alpha_ac:.3f}° lies outside the swept range "
            f"[{a_lo:.2f}°, {a_hi:.2f}°]. The target CL is not reachable "
            "inside the sweep, so design-point values are extrapolated. "
            "Widen the α range.")

    # A clamping interpolator returns an in-range α that does not actually
    # meet the target, so the achieved CL is checked as well as the range.
    if cfg["sweep"]["design_alpha_mode"] == "target_CL":
        key = "CL_aircraft" if "CL_aircraft" in design_vals else "cl_airfoil"
        achieved = float(design_vals[key])
        target = float(cfg["design"]["target_CL"])
        if abs(achieved - target) > max(0.02 * target, 1e-4):
            warnings.append(
                f"Target CL = {target:.4f} was not met: the design point "
                f"gives {achieved:.4f}. The target is not attainable inside "
                f"the swept α range [{a_lo:.2f}°, {a_hi:.2f}°], so widen the "
                "sweep or change the target.")

    cl_max_est = approx_cl_max(Re)
    if design_vals["cl_airfoil"] > cl_max_est:
        warnings.append(
            f"Design Cl = {design_vals['cl_airfoil']:.3f} exceeds the "
            f"approximate Re-based Cl_max ({cl_max_est:.2f}). A real airfoil "
            "is likely stalled here; treat the L/D value with caution.")

    tmpdir = Path(tempfile.mkdtemp(prefix="joukowski_run_"))
    try:
        chord_dim = wing["root_chord"] if wing is not None else 1.0
        export_airfoil_files(best, tmpdir, chord_dim=chord_dim, tag="root")

        if wing is not None:
            x_n, z_n, _, _ = generate_joukowski_airfoil(
                best["a"], best["x_c"], best["y_c"], n_points=1800)
            x_ord, z_ord = reorder_airfoil_from_trailing_edge(x_n, z_n)
            np.savetxt(
                tmpdir / "airfoil_tip_dimensional_m.dat",
                np.column_stack((x_ord * wing["tip_chord"],
                                 z_ord * wing["tip_chord"])),
                fmt="%.9f",
                header=f"x [m]    z [m]  (chord = {wing['tip_chord']:.6f} m)",
                comments="")

        export_sweep_csv(sweep, tmpdir, "alpha_sweep.csv",
                         include_wing=(wing is not None))

        design_section_alpha = design_alpha_ac + (
            aircraft["wing_incidence_deg"] if aircraft is not None else 0.0)
        x_cp, z_cp, cp_ord = export_cp_distribution(
            best, design_section_alpha, tmpdir)

        if wing is not None:
            export_wing_files(best, wing, tmpdir)

        write_summary_sheet(best, wing, aircraft, sweep, design_vals,
                            cfg, tmpdir, warnings)
        write_run_manifest(cfg, tmpdir, warnings)

        files = {p.name: p.read_bytes() for p in sorted(tmpdir.iterdir())
                 if p.is_file()}
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)

    return dict(
        best=best, wing=wing, aircraft=aircraft, sweep=sweep,
        design_vals=design_vals, design_alpha_ac=design_alpha_ac,
        design_section_alpha=design_section_alpha,
        warnings=warnings, files=files,
        cp_x=np.asarray(x_cp), cp_z=np.asarray(z_cp), cp_val=np.asarray(cp_ord),
        chord_dim=chord_dim,
        # Deep copy: the original stored dict(cfg), a shallow copy whose nested
        # dicts kept mutating as the user moved the widgets, so the "snapshot"
        # in the report did not match the run.
        cfg_snapshot=copy.deepcopy(cfg),
        cl_max_est=cl_max_est,
        run_key=run_key_of(cfg),
        finished_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )


if run_clicked:
    problems = validate(cfg)
    if problems:
        for p in problems:
            st.error(p)
    else:
        try:
            with st.spinner("Optimizing airfoil, sweeping AoA, writing outputs..."):
                st.session_state.results = run_design(cfg)
            st.success("Design complete.")
        except Exception as exc:
            st.session_state.results = None
            st.error(f"Pipeline failed: {type(exc).__name__}: {exc}")
            with st.expander("Traceback"):
                import traceback
                st.code(traceback.format_exc(), language="text")


# =========================================================================
# CACHED FIGURE BUILDERS
# Leading-underscore arguments are excluded from Streamlit's cache hashing;
# run_key and the control values carry the identity instead. Only the Plotly
# figures are cached - matplotlib figures are consumed by st.pyplot with
# clear_figure=True, so a cached one would come back blank.
# =========================================================================
@st.cache_data(show_spinner=False, max_entries=12)
def fig_surface_cached(_best, _wing, run_key, n_span, z_exagg, z_floor, edges):
    return P.fig3d_wing_surface(_best, _wing, n_span=n_span, z_exagg=z_exagg,
                                z_floor=z_floor, show_edges=edges)


@st.cache_data(show_spinner=False, max_entries=12)
def fig_ribs_cached(_best, _wing, run_key, n_ribs, z_exagg, z_floor):
    return P.fig3d_wing_ribs(_best, _wing, n_ribs=n_ribs, z_exagg=z_exagg,
                             z_floor=z_floor)


@st.cache_data(show_spinner=False, max_entries=12)
def fig_cp3d_cached(_best, _wing, _cp, run_key, n_span, z_exagg, z_floor, alpha_sec):
    return P.fig3d_wing_cp(_best, _wing, _cp, n_span=n_span, z_exagg=z_exagg,
                           z_floor=z_floor, alpha_sec=alpha_sec)


@st.cache_data(show_spinner=False, max_entries=12)
def fig_load3d_cached(_wing, run_key, CL):
    return P.fig3d_spanwise_loading(_wing, CL)


@st.cache_data(show_spinner=False, max_entries=6)
def figure_pngs_cached(_res, run_key):
    """Render every 2-D figure and the static 3-D view to PNG, once per run."""
    best, wing, sweep = _res["best"], _res["wing"], _res["sweep"]
    d_a = _res["design_alpha_ac"]
    out = {}
    builders = {
        "fig_airfoil_shape.png": lambda: P.fig_airfoil_shape(best, _res["chord_dim"]),
        "fig_thickness_camber.png": lambda: P.fig_thickness_camber(best),
        "fig_cp_distribution.png": lambda: P.fig_cp(
            _res["cp_x"], _res["cp_val"], _res["design_section_alpha"],
            best["max_mach"]),
        "fig_polar_cl.png": lambda: P.fig_cl_polar(sweep, best, d_a),
        "fig_polar_cd.png": lambda: P.fig_cd_polar(sweep, best, d_a),
        "fig_polar_ld.png": lambda: P.fig_ld_polar(sweep, best, d_a),
        "fig_polar_cm.png": lambda: P.fig_cm_polar(sweep, best, d_a),
        "fig_drag_polar.png": lambda: P.fig_drag_polar(sweep, d_a),
    }
    if wing is not None:
        CL = _res["design_vals"].get("CL_aircraft",
                                     _res["design_vals"]["cl_airfoil"])
        builders["fig_spanwise_loading_schrenk.png"] = \
            lambda: P.fig_spanwise_loading(wing, CL, best["Re"])
        builders["fig_wing_3d.png"] = lambda: P.fig_wing_3d_static(best, wing)
    for name, build in builders.items():
        fig = build()
        out[name] = P.fig_to_png(fig, tight=not name.startswith("fig_wing_3d"))
        P.plt.close(fig)
    return out


@st.cache_data(show_spinner=False, max_entries=6)
def zip_bundle_cached(_files, _pngs, run_key):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, data in _files.items():
            zf.writestr(name, data)
        for name, data in _pngs.items():
            zf.writestr(f"figures/{name}", data)
    buf.seek(0)
    return buf.getvalue()


# =========================================================================
# RESULTS
# =========================================================================
def render_results(res):
    best = res["best"]
    wing = res["wing"]
    sweep = res["sweep"]
    dv = res["design_vals"]
    d_a = res["design_alpha_ac"]
    warns = res["warnings"]
    files = res["files"]
    run_key = res["run_key"]

    st.divider()
    st.subheader("Results")

    for w in warns:
        st.warning(w)

    st.markdown(f"**Design point** — aircraft α = **{d_a:.3f}°** · "
                f"section α = **{res['design_section_alpha']:.3f}°**")

    def _fmt(v, prec=4):
        return f"{v:.{prec}f}" if v is not None else "—"

    if wing is not None:
        m = st.columns(6)
        m[0].metric("CL aircraft", _fmt(dv.get("CL_aircraft"), 4))
        m[1].metric("CD aircraft", _fmt(dv.get("CD_aircraft"), 5))
        m[2].metric("L/D aircraft", _fmt(dv.get("LD_aircraft"), 2))
        m[3].metric("Cm at CG", _fmt(dv.get("Cm_aircraft"), 5))
        m[4].metric("Cl 2-D airfoil", _fmt(dv["cl_airfoil"], 4))
        m[5].metric("L/D 2-D", _fmt(dv["ld_airfoil"], 2))
    else:
        m = st.columns(4)
        m[0].metric("Cl airfoil", _fmt(dv["cl_airfoil"], 4))
        m[1].metric("Cd airfoil", _fmt(dv["cd_airfoil"], 5))
        m[2].metric("L/D", _fmt(dv["ld_airfoil"], 2))
        m[3].metric("Cm at c/4", _fmt(dv["Cm_airfoil"], 5))

    # Tabs keyed by name - the original computed tab indices by hand and
    # shifted them when the 3-D tab appeared.
    labels = ["Summary", "Airfoil (2-D)", "Polars"]
    if wing is not None:
        labels.append("3-D wing")
    labels += ["Data tables", "Downloads"]
    tabs = dict(zip(labels, st.tabs(labels)))

    # ---------------- SUMMARY ----------------
    with tabs["Summary"]:
        cfg_s = res["cfg_snapshot"]
        st.markdown("##### Run information")
        m1, m2, m3, m4 = st.columns(4)
        m1.markdown(f"**Generated**  \n{res['finished_at']}")
        m2.markdown(f"**Engine version**  \n{VERSION}")
        m3.markdown(f"**Flow regime**  \n{best['flow_regime']}")
        m4.markdown(f"**Design mode**  \n{cfg_s['sweep']['design_alpha_mode']}")
        st.divider()

        st.markdown("##### Inputs")
        input_rows = [
            ("Mach number", f"{cfg_s['flow']['mach']:.4f}"),
            ("Reynolds number",
             f"{cfg_s['flow']['reynolds']:.3e} "
             f"(ref: {cfg_s['flow']['reynolds_reference']})"),
            ("Boundary-layer mode", cfg_s["flow"]["flow_regime_manual"]),
        ]
        if cfg_s["flow"]["flow_regime_manual"] == "mixed":
            input_rows.append(("Transition x/c",
                               f"{cfg_s['flow']['transition_xc']:.3f}"))
        input_rows += [
            ("α sweep [deg]",
             f"{cfg_s['sweep']['alpha_start_deg']:.2f} → "
             f"{cfg_s['sweep']['alpha_end_deg']:.2f} "
             f"(step {cfg_s['sweep']['alpha_step_deg']:.3f})"),
            ("Target CL", f"{cfg_s['design']['target_CL']:.4f}"),
        ]
        show_df(pd.DataFrame(input_rows, columns=["Parameter", "Value"]))
        st.divider()

        st.markdown("##### Optimized geometry")
        c1, c2 = st.columns(2)
        with c1:
            st.markdown("**Airfoil**")
            show_df(pd.DataFrame({
                "Property": ["Joukowski a", "Circle centre x_c",
                             "Circle centre y_c", "Circle radius R",
                             "Target t/c [%]", "Actual t/c [%]",
                             "Max camber/c [%]", "Zero-lift angle [deg]",
                             "Section lift slope [1/rad]"],
                "Value": [f"{best['a']:.6f}", f"{best['x_c']:.6f}",
                          f"{best['y_c']:.6f}", f"{best['R']:.6f}",
                          f"{100 * best['tc_target']:.3f}",
                          f"{100 * best['tc_actual']:.3f}",
                          f"{100 * best['camber']:.3f}",
                          f"{best['alpha0_deg']:.3f}",
                          f"{best['a0_section']:.4f}"]}))
        with c2:
            if wing is not None:
                st.markdown("**Wing**")
                show_df(pd.DataFrame({
                    "Property": ["Span [m]", "Root chord [m]", "Tip chord [m]",
                                 "Area [m²]", "Aspect ratio", "MAC [m]",
                                 "Sweep LE [deg]", "Sweep c/4 [deg]",
                                 "Dihedral [deg]", "Oswald efficiency",
                                 "Finite-wing lift slope [1/rad]"],
                    "Value": [f"{wing['span']:.4f}", f"{wing['root_chord']:.4f}",
                              f"{wing['tip_chord']:.4f}", f"{wing['area']:.4f}",
                              f"{wing['aspect_ratio']:.4f}", f"{wing['MAC']:.4f}",
                              f"{wing['sweep_le_deg']:.2f}",
                              f"{wing['sweep_qc_deg']:.2f}",
                              f"{wing['dihedral_deg']:.2f}",
                              f"{wing['oswald_e']:.4f}",
                              f"{best['a_wing']:.4f}"]}))
            else:
                st.markdown("**Wing**")
                st.info("3-D mode is off, so no wing geometry was produced.")

        st.divider()
        st.markdown("##### Performance at the design AoA")
        st.caption(f"Aircraft α = {d_a:.4f}° · section α = "
                   f"{res['design_section_alpha']:.4f}°")

        perf_2d = [
            ("Cl", f"{dv['cl_airfoil']:.6f}"),
            ("Cd (total)", f"{dv['cd_airfoil']:.6f}"),
            ("Cd viscous (Cf × FF)",
             f"{dv.get('cd_viscous_const', best['Cd_viscous']):.6f}"),
            ("Cd wave", f"{dv['cd_wave']:.6f}"),
            ("L/D", f"{dv['ld_airfoil']:.4f}"),
            ("Cm about c/4", f"{dv['Cm_airfoil']:.6f}"),
        ]
        if "CL_aircraft" in dv:
            c1, c2, c3 = st.columns(3)
            with c1:
                st.markdown("**2-D airfoil**")
                show_df(pd.DataFrame(perf_2d, columns=["Quantity", "Value"]))
            with c2:
                st.markdown("**3-D wing**")
                show_df(pd.DataFrame([
                    ("CL", f"{dv['CL_wing']:.6f}"),
                    ("CDi (induced)", f"{dv['CDi_wing']:.6f}"),
                    ("CD", f"{dv['CD_wing']:.6f}"),
                    ("L/D", f"{dv['LD_wing']:.4f}"),
                ], columns=["Quantity", "Value"]))
            with c3:
                st.markdown("**Preliminary aircraft**")
                show_df(pd.DataFrame([
                    ("CL", f"{dv['CL_aircraft']:.6f}"),
                    ("CD", f"{dv['CD_aircraft']:.6f}"),
                    ("L/D", f"{dv['LD_aircraft']:.4f}"),
                    ("Cm at CG", f"{dv['Cm_aircraft']:.6f}"),
                ], columns=["Quantity", "Value"]))
        else:
            st.markdown("**2-D airfoil**")
            show_df(pd.DataFrame(perf_2d, columns=["Quantity", "Value"]))

        if warns:
            st.divider()
            st.markdown("##### Warnings raised by this run")
            for w in warns:
                st.warning(w)

        st.divider()
        st.markdown("##### Export")
        c1, c2 = st.columns([1, 3])
        if "SUMMARY_SHEET.txt" in files:
            with c1:
                st.download_button(
                    "Download summary as TXT", data=files["SUMMARY_SHEET.txt"],
                    file_name="SUMMARY_SHEET.txt", mime="text/plain",
                    key="dl_summary_tab", **FILL_DL)
            with c2:
                with st.expander("View the raw summary file"):
                    st.code(files["SUMMARY_SHEET.txt"].decode("utf-8", "replace"),
                            language="text")

    # ---------------- AIRFOIL ----------------
    with tabs["Airfoil (2-D)"]:
        st.pyplot(P.fig_airfoil_shape(best, res["chord_dim"]), clear_figure=True)
        st.pyplot(P.fig_thickness_camber(best), clear_figure=True)
        st.pyplot(P.fig_cp(res["cp_x"], res["cp_val"],
                           res["design_section_alpha"], best["max_mach"]),
                  clear_figure=True)
        st.caption(
            "Cp comes from the potential-flow solution at the design section "
            "α, so it carries no boundary layer and no shock. Where the curve "
            "crosses Cp*, the local flow is sonic and the inviscid result "
            "stops being trustworthy."
        )

    # ---------------- POLARS ----------------
    with tabs["Polars"]:
        c1, c2 = st.columns(2)
        with c1:
            st.pyplot(P.fig_cl_polar(sweep, best, d_a), clear_figure=True)
            st.pyplot(P.fig_ld_polar(sweep, best, d_a), clear_figure=True)
        with c2:
            st.pyplot(P.fig_cd_polar(sweep, best, d_a), clear_figure=True)
            st.pyplot(P.fig_cm_polar(sweep, best, d_a), clear_figure=True)
        st.divider()
        st.pyplot(P.fig_drag_polar(sweep, d_a), clear_figure=True)
        st.caption(
            "The lift curve is linear by construction — there is no stall "
            "model — so everything above the approximate Cl_max line is "
            "extrapolation, not prediction."
        )

    # ---------------- 3-D WING ----------------
    if wing is not None:
        with tabs["3-D wing"]:
            st.markdown("##### View controls")
            c1, c2, c3 = st.columns([2, 1.3, 1.3])
            with c1:
                view = st.radio(
                    "View", ["Solid surface", "Section ribs",
                             "Surface pressure (Cp)", "Spanwise load"],
                    horizontal=True, key="view3d",
                    help="One 3-D view at a time keeps the browser responsive.")
            with c2:
                scale_opts = {
                    "Readable (auto)": (1.0, 0.16),
                    "True scale": (1.0, 0.0),
                    "Stretch ×3": (3.0, 0.16),
                    "Stretch ×6": (6.0, 0.16),
                }
                scale_lbl = st.selectbox("Vertical scale",
                                         list(scale_opts.keys()), index=0,
                                         key="zscale3d")
                z_exagg, z_floor = scale_opts[scale_lbl]
            with c3:
                mesh = st.select_slider(
                    "Mesh density", options=["Coarse", "Normal", "Fine"],
                    value="Normal", key="mesh3d")
            n_span = {"Coarse": 21, "Normal": 41, "Fine": 71}[mesh]

            st.caption(
                "Drag to rotate, scroll to zoom, and use the camera icon to "
                "save a PNG. True scale shows the real thickness-to-span "
                "ratio, which is why the section detail disappears; any other "
                "setting stretches the drawing only — the z tick values stay "
                "in true metres and the axis title states the factor."
            )

            if view == "Solid surface":
                fig = fig_surface_cached(best, wing, run_key, n_span,
                                         z_exagg, z_floor, True)
                st.plotly_chart(fig, config=PLOTLY_CONFIG, **FILL_PLOTLY)
                st.caption(
                    "The optimized section scaled along the trapezoidal "
                    "planform from root to tip, with leading-edge sweep and "
                    "dihedral applied. This is the same geometry written to "
                    "the wing surface files in the Downloads tab."
                )
            elif view == "Section ribs":
                fig = fig_ribs_cached(best, wing, run_key,
                                      max(n_span // 4, 5), z_exagg, z_floor)
                st.plotly_chart(fig, config=PLOTLY_CONFIG, **FILL_PLOTLY)
                st.caption(
                    "Discrete section stations with the leading edge, "
                    "trailing edge and quarter-chord line. This is the view "
                    "to check before lofting the surface in CAD."
                )
            elif view == "Surface pressure (Cp)":
                fig = fig_cp3d_cached(best, wing, res["cp_val"], run_key,
                                      n_span, z_exagg, z_floor,
                                      float(res["design_section_alpha"]))
                st.plotly_chart(fig, config=PLOTLY_CONFIG, **FILL_PLOTLY)
                st.warning(
                    "Strip approximation. The same 2-D section Cp is painted "
                    "at every spanwise station, so there is no spanwise "
                    "pressure variation, no sweep relief and no tip effect in "
                    "this colouring. It shows the chordwise pressure field "
                    "wrapped onto the 3-D shape, not a 3-D pressure solution."
                )
            else:
                CL_plot = dv.get("CL_aircraft", dv["cl_airfoil"])
                fig = fig_load3d_cached(wing, run_key, float(CL_plot))
                st.plotly_chart(fig, config=PLOTLY_CONFIG, **FILL_PLOTLY)
                st.caption(
                    "Load height is normalized, not metres. The planform "
                    "outline is drawn flat at z = 0 for reference."
                )

            st.divider()
            st.markdown("##### Spanwise lift distribution")
            CL_span = dv.get("CL_aircraft", dv["cl_airfoil"])
            st.pyplot(P.fig_spanwise_loading(wing, CL_span, best["Re"]),
                      clear_figure=True)
            st.info(
                "Schrenk approximation, computed here in the UI rather than by "
                "the engine: the load is the average of the chord distribution "
                "and an ellipse of equal area. It ignores sweep, twist and "
                "compressibility, so use it as a first-cut tip-stall check "
                "only — where the local cl curve approaches Cl_max is where "
                "stall starts. A lifting-line or vortex-lattice solution is "
                "the next step up."
            )

            with st.expander("Static 3-D view for reports (PNG)"):
                st.pyplot(P.fig_wing_3d_static(best, wing, z_exagg=z_exagg),
                          clear_figure=True)
                st.caption(
                    "Fixed-camera matplotlib version of the same geometry, "
                    "included in the ZIP as figures/fig_wing_3d.png. This one "
                    "is always drawn at a readable vertical scale so the axis "
                    "labels stay legible; the factor is stated in the z axis "
                    "title."
                )

    # ---------------- DATA TABLES ----------------
    with tabs["Data tables"]:
        st.markdown("**AoA sweep**")
        alpha_df = pd.DataFrame({
            "α_aircraft [deg]": sweep["alpha_aircraft"],
            "α_section [deg]": sweep["alpha_section"],
            "Cl_airfoil": sweep["cl_airfoil"],
            "Cd_airfoil": sweep["cd_airfoil"],
            "L/D_airfoil": sweep["ld_airfoil"],
            "Cm_airfoil": sweep["Cm_airfoil"],
        })
        if "CL_aircraft" in sweep:
            alpha_df["CL_aircraft"] = sweep["CL_aircraft"]
            alpha_df["CD_aircraft"] = sweep["CD_aircraft"]
            alpha_df["L/D_aircraft"] = sweep["LD_aircraft"]
            alpha_df["Cm_aircraft"] = sweep["Cm_aircraft"]
        show_df(alpha_df, height=350, index=True)

        st.markdown("**Thickness / camber distribution** "
                    f"(at chord = {res['chord_dim']:.3f} m)")
        tc_name = "airfoil_root_thickness_camber.csv"
        if tc_name in files:
            show_df(pd.read_csv(io.BytesIO(files[tc_name])), height=300, index=True)
        else:
            st.info(f"`{tc_name}` was not produced by this run.")

        if wing is not None:
            st.markdown("**Spanwise loading (Schrenk estimate)**")
            CL_span = dv.get("CL_aircraft", dv["cl_airfoil"])
            y, c_local, c_ell, cl_local = P.schrenk_loading(wing, CL_span, n=61)
            show_df(pd.DataFrame({
                "y [m]": y,
                "chord c(y) [m]": c_local,
                "elliptic equivalent [m]": c_ell,
                "local cl": cl_local,
                "local cl / CL": cl_local / max(CL_span, 1e-9),
            }), height=280, index=True)

    # ---------------- DOWNLOADS ----------------
    with tabs["Downloads"]:
        st.markdown("Everything this run produced, plus PNG copies of the "
                    "figures.")
        pngs = figure_pngs_cached(res, run_key)
        zip_bytes = zip_bundle_cached(files, pngs, run_key)

        st.download_button(
            "Download everything as ZIP", data=zip_bytes,
            file_name=(f"joukowski_run_{run_key}_"
                       f"{datetime.now().strftime('%Y%m%d_%H%M%S')}.zip"),
            mime="application/zip", type="primary",
            key="dl_zip", **FILL_DL)

        st.divider()
        st.markdown("**Individual files**")

        groups = {
            "Airfoil coordinates and geometry": [],
            "Sweep data and Cp distribution": [],
            "Wing / 3-D": [],
            "Figures (PNG)": [],
            "Reports and manifest": [],
        }
        for name in files:
            if name.startswith("airfoil"):
                groups["Airfoil coordinates and geometry"].append((name, files[name]))
            elif name.startswith(("wing", "half_wing")):
                groups["Wing / 3-D"].append((name, files[name]))
            elif "sweep" in name or "cp_distribution" in name:
                groups["Sweep data and Cp distribution"].append((name, files[name]))
            else:
                groups["Reports and manifest"].append((name, files[name]))
        for name, data in pngs.items():
            groups["Figures (PNG)"].append((name, data))

        for group_name, items in groups.items():
            if not items:
                continue
            with st.expander(group_name, expanded=(group_name != "Figures (PNG)")):
                for name, data in items:
                    c1, c2 = st.columns([3, 1])
                    with c1:
                        st.write(f"`{name}` · {len(data):,} bytes")
                    with c2:
                        st.download_button(
                            "Download", data=data, file_name=name,
                            key=f"dl_{run_key}_{name}", **FILL_DL)


if st.session_state.results is not None:
    render_results(st.session_state.results)
else:
    st.info("Set the inputs above, then click **Run design**.")

st.divider()
st.caption(
    f"Joukowski Airfoil & Wing Designer · engine v{VERSION} · "
    "Preliminary conceptual model. Validate with XFOIL, CFD or wind-tunnel "
    "data before committing to a design."
)
